sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0

  # 开发文件上传接口
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEJ4BgN1hiqAkn8V65Z
    access-key-secret: OxIXLWDzj8qLYMHcrjPUnGybw1oZI5
    bucket-name: java-study-sky-take-out2024